# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='评论所属文章'),
        ),
    ]
